const DEVINFO_GETDEV = 'DEVINFO_GETDEV'  //获取设备信息
const SMETMET= 'SMETMET' //设置地图
const ADDMARKERS = 'ADDMARKERS' //添加点标记
const CREAT_MARKERS = 'CREAT_MARKERS' //创建点标记
const SER_DEVBY = 'SER_DEVBY'


export{
   DEVINFO_GETDEV,
   SMETMET,
   ADDMARKERS,
   CREAT_MARKERS,
   SER_DEVBY
}